# Generated by Django 4.2.16 on 2025-06-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_author_ratingauthor_alter_comment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('art', 'Статья'), ('news', 'Новость')], db_column='categorytype', default='news', max_length=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='postAuthor',
            field=models.ForeignKey(db_column='postauthor_id', on_delete=django.db.models.deletion.CASCADE, to='news.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_in_Post',
            field=models.DateTimeField(auto_now_add=True, db_column='time_in_post'),
        ),
    ]
